import type { LessonMeta } from "./types";

/**
 * The lesson-level map for the 12-month themed curriculum (see
 * lib/curriculum/months.ts). Every month has exactly FOUR lessons, one per
 * week — a standalone, full class plan each, matching a once-a-week class
 * cadence rather than a single monthly "unit":
 *
 * - `week1` — introduces the month's vocabulary, sentence pattern, and AI
 *   big idea through Vora.
 * - `week2` / `week3` — each builds a full lesson (its own light vocab
 *   recap, a short concept reinforcement, one game, a formative check)
 *   around one of the month's two games, so playing is still teaching, not
 *   just playing.
 * - `week4` — speaking-confidence + review week (a sentence/chant
 *   production task, or a quarter-checkpoint listening review).
 *
 * See lib/curriculum/lessons/month1.ts..month12.ts for the full authored
 * segment content, and docs/MONTHLY_CURRICULUM.md for the teacher-facing
 * map this mirrors.
 */
export const MONTHLY_SCOPE_AND_SEQUENCE: LessonMeta[] = [
  // ==================== Month 1 — Space ====================
  {
    key: "m1_week1",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week1",
    title: "It's a Star!",
    bigIdeas: ["reasoning", "learning"],
    englishFocus: "Space nouns + \"It's a ___.\"",
    koreanL1Note:
      "\"It's a ___\" reuses the copula pattern from the foundations unit (Week 1) — a good check for whether that structure stuck, now with brand-new vocabulary.",
    objectives: [
      "I can name five things in space.",
      "I can explain that Vora finds patterns in pictures of stars, the same way it sorts other pictures.",
    ],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — pattern-finding in images, introduced with space as the concrete example.",
  },
  {
    key: "m1_week2",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week2",
    title: "Space Thing or Earth Thing?",
    bigIdeas: ["perception"],
    englishFocus: "Space vocab review inside a sort-the-picture game.",
    koreanL1Note: "Same vocabulary as Week 1, new mechanic — repetition across a different interaction is the goal, not new grammar.",
    objectives: ["I can sort pictures into 'space thing' and 'earth thing,' and check Vora's guesses."],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — a second, playful pass at the classification loop from Week 1.",
  },
  {
    key: "m1_week3",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week3",
    title: "Space Word Match",
    bigIdeas: ["learning"],
    englishFocus: "Space vocab review inside a flip-card matching game.",
    koreanL1Note: "Third exposure to this month's vocabulary set — recognition/recall practice complements Week 1's production practice.",
    objectives: ["I can find matching space word-picture pairs."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure is literally how both kids and Vora get better at recognizing something.",
  },
  {
    key: "m1_week4",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week4",
    title: "I See a Rocket!",
    bigIdeas: [],
    englishFocus: "\"I see a ___.\" sentence production.",
    koreanL1Note: "First production (not just recognition) of a full 3-word sentence with this month's nouns — build it tile-by-tile before asking for free speech.",
    objectives: ["I can say \"I see a ___\" about a space picture."],
    standardsNote: "Week 4 speaking-confidence pillar — short, low-stakes, one sentence pattern produced out loud by every child.",
  },

  // ==================== Month 2 — Culture & Countries ====================
  {
    key: "m2_week1",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week1",
    title: "Hello, World!",
    bigIdeas: ["societal_impact"],
    englishFocus: "Country/food/dance nouns + \"I'm from ___.\"",
    koreanL1Note: "\"I'm from Korea\" gives kids a sentence about themselves that's true and easy to be proud of — start here before other countries.",
    objectives: [
      "I can name three countries and say \"I'm from ___.\"",
      "I can explain that translator apps use AI to help people who speak different languages understand each other.",
    ],
    standardsNote: "AI4K12 Big Idea 5 (Societal Impact) — machine translation as a concrete, kid-relatable example of AI's real-world reach.",
  },
  {
    key: "m2_week2",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week2",
    title: "A Pretend Trip",
    bigIdeas: ["reasoning"],
    englishFocus: "Ordering a travel routine.",
    koreanL1Note: "Sequencing words (first/next/then/last) get reused from the foundations unit inside a brand-new routine — a good transfer check.",
    objectives: ["I can order the steps of a pretend trip."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — ordered steps as a concrete algorithm, transferred to a new routine.",
  },
  {
    key: "m2_week3",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week3",
    title: "World Word Match",
    bigIdeas: ["learning"],
    englishFocus: "World vocab review inside a flip-card matching game.",
    koreanL1Note: "Third exposure to this month's vocabulary, recognition/recall practice after Week 1's production and Week 2's sequencing.",
    objectives: ["I can match world vocabulary to pictures."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m2_week4",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week4",
    title: "I'm from Korea!",
    bigIdeas: [],
    englishFocus: "\"I'm from ___.\" sentence production.",
    koreanL1Note: "Contraction practice (\"I'm\" = \"I am\") — Korean has no equivalent contraction, model it as one chunk, not two words squeezed together.",
    objectives: ["I can say \"I'm from Korea\" with confidence."],
    standardsNote: "Week 4 speaking-confidence pillar — a sentence every child can say truthfully about themselves.",
  },

  // ==================== Month 3 — Friends ====================
  {
    key: "m3_week1",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week1",
    title: "Making a Friend",
    bigIdeas: ["natural_interaction"],
    englishFocus: "Friendship phrases + \"Can I play?\" / \"Let's share.\"",
    koreanL1Note: "\"Can I ___?\" fronts an auxiliary the same way \"Do you ___?\" did in the foundations unit — call out the pattern explicitly so it transfers.",
    objectives: [
      "I can ask \"Can I play?\" and offer to share.",
      "I can explain that a voice assistant listens for me to stop talking before it answers, like a good friend takes turns.",
    ],
    standardsNote: "AI4K12 Big Idea 4 (Natural Interaction) — turn-taking in conversation, framed through friendship rather than technology first.",
  },
  {
    key: "m3_week2",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week2",
    title: "Can I play?",
    bigIdeas: [],
    englishFocus: "Building the \"Can I play?\" sentence tile-by-tile.",
    koreanL1Note: "Reinforces \"Can I play?\" as a fixed chunk kids can produce quickly, now built word-by-word so the word order is visible.",
    objectives: ["I can build the sentence \"Can I play?\" in the right word order."],
    standardsNote: "Extends Week 1's natural-interaction thread into English word-order practice.",
  },
  {
    key: "m3_week3",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week3",
    title: "Feelings Match",
    bigIdeas: ["learning"],
    englishFocus: "Matching feeling words to faces.",
    koreanL1Note: "New, smaller vocabulary set (happy/sad/kind) previewing Month 11's Emotions theme — light exposure now, full unit later.",
    objectives: ["I can match a feeling word to a face."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — recognition practice through repeated matching.",
  },
  {
    key: "m3_week4",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week4",
    title: "Listen Closely: light or right?",
    bigIdeas: ["perception"],
    englishFocus: "/r/ vs /l/ minimal-pair listening review.",
    koreanL1Note: "Quarter-checkpoint review of the single highest-frequency Korean-learner sound gap (see docs/KOREAN_L1_NOTES.md) — spaced repetition from the foundations unit.",
    objectives: ["I can listen and pick the word I hear: light or right."],
    standardsNote: "Week 4 pillar, listening-discrimination variant — every third month reviews one of the four core Korean L1 sound gaps.",
  },

  // ==================== Month 4 — Environment ====================
  {
    key: "m4_week1",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week1",
    title: "Take Care of Earth",
    bigIdeas: ["learning", "societal_impact"],
    englishFocus: "Nature nouns + \"We should / shouldn't ___.\"",
    koreanL1Note: "Modal \"should\" has no verb-final counterpart to lean on, same challenge as \"can\" in the foundations unit — model as a fixed chunk first.",
    objectives: [
      "I can say one thing we should do and one thing we shouldn't do for the earth.",
      "I can explain that AI helps scientists learn about our climate by studying huge amounts of weather data.",
    ],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — learning from large datasets, introduced through climate science.",
  },
  {
    key: "m4_week2",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week2",
    title: "Recycling Steps",
    bigIdeas: ["reasoning"],
    englishFocus: "Ordering the steps of recycling.",
    koreanL1Note: "Reinforces first/next/then/last from the foundations unit inside a new, real-world routine.",
    objectives: ["I can put the steps of recycling in the right order."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — an algorithm is an exact, ordered list of steps.",
  },
  {
    key: "m4_week3",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week3",
    title: "What Comes Next?",
    bigIdeas: ["reasoning", "learning"],
    englishFocus: "Predicting a simple growth pattern.",
    koreanL1Note: "Reuses the pattern-prediction mechanic first introduced in Month 1 — a good transfer check across a very different theme.",
    objectives: ["I can guess what comes next in a pattern."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — a second, playful pass at pattern-based prediction.",
  },
  {
    key: "m4_week4",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week4",
    title: "We Should Recycle!",
    bigIdeas: [],
    englishFocus: "\"We should ___.\" sentence production.",
    koreanL1Note: "First group-subject sentence (\"we,\" not \"I\") — a small but genuine shift kids should hear called out.",
    objectives: ["I can say one thing \"we should\" do for the earth."],
    standardsNote: "Week 4 speaking-confidence pillar — closes the environment theme on a sentence kids can repeat at home.",
  },

  // ==================== Month 5 — Family ====================
  {
    key: "m5_week1",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week1",
    title: "This Is My Family",
    bigIdeas: ["perception"],
    englishFocus: "Family nouns + \"This is my ___.\"",
    koreanL1Note: "Korean family terms encode relative age/side of family with no single English equivalent — validate kids who want more precision than 'brother/sister' gives them, don't correct it away.",
    objectives: [
      "I can introduce four family members in English.",
      "I can explain that face-recognition apps sometimes mix up people who look alike, unlike how I always know my own family.",
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — the limits of computer vision, made concrete and reassuring rather than scary.",
  },
  {
    key: "m5_week2",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week2",
    title: "This is my brother.",
    bigIdeas: [],
    englishFocus: "Building \"This is my ___\" sentences tile-by-tile.",
    koreanL1Note: "Repeats the possessive \"my\" from the foundations unit's classroom-objects lesson, now with people instead of things.",
    objectives: ["I can build a sentence introducing a family member."],
    standardsNote: "Extends Week 1's family vocabulary into sentence-building practice.",
  },
  {
    key: "m5_week3",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week3",
    title: "Family Word or School Word?",
    bigIdeas: ["perception"],
    englishFocus: "Sorting family words vs. school words.",
    koreanL1Note: "A gentle classification loop, distinguishing this month's vocabulary from an already-known category (school, from the foundations unit).",
    objectives: ["I can sort words into 'family' and 'school,' and check Vora's guesses."],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — classification practice against a contrasting, already-familiar category.",
  },
  {
    key: "m5_week4",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week4",
    title: "This Is My Sister!",
    bigIdeas: [],
    englishFocus: "\"This is my ___.\" sentence production.",
    koreanL1Note: "Kids may want to name a cousin, grandparent, or pet — welcome any real family member, the sentence frame is what matters.",
    objectives: ["I can proudly introduce one real family member in English."],
    standardsNote: "Week 4 speaking-confidence pillar — personal, low-stakes production about something every child has an honest answer for.",
  },

  // ==================== Month 6 — Animals ====================
  {
    key: "m6_week1",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week1",
    title: "Wild Animals",
    bigIdeas: ["perception"],
    englishFocus: "Wild animal nouns + \"It's a big / small ___.\"",
    koreanL1Note: "Adjective-before-noun order (\"a big lion\") matches Korean word order — call this out as an easy win, not everything is a hard shift.",
    objectives: [
      "I can name five wild animals and describe them as big or small.",
      "I can explain that wildlife cameras use AI to recognize which animal walked by, the same sorting idea as Vora's games.",
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — a real deployed use of image classification kids can picture concretely (a camera trap in a forest).",
  },
  {
    key: "m6_week2",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week2",
    title: "What Comes Next?",
    bigIdeas: ["reasoning"],
    englishFocus: "Predicting an animal pattern.",
    koreanL1Note: "Pattern words like \"same/different\" carry over from the foundations unit's colors-and-patterns week.",
    objectives: ["I can guess what comes next in an animal pattern."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — a playful reintroduction of pattern-based prediction.",
  },
  {
    key: "m6_week3",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week3",
    title: "Animal Words",
    bigIdeas: ["learning"],
    englishFocus: "Animal vocab review inside a flip-card matching game.",
    koreanL1Note: "Third exposure to this month's vocabulary set — recognition/recall practice.",
    objectives: ["I can match animal words to pictures."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m6_week4",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week4",
    title: "Listen Closely: fan or pan?",
    bigIdeas: ["perception"],
    englishFocus: "/f/ vs /p/ minimal-pair listening review.",
    koreanL1Note: "Second quarter-checkpoint review — Korean has no /f/ phoneme, so this contrast is genuinely new, not just underused, and benefits from repeated exposure across the year.",
    objectives: ["I can listen and pick the word I hear: fan or pan."],
    standardsNote: "Week 4 pillar, listening-discrimination variant.",
  },

  // ==================== Month 7 — Weather ====================
  {
    key: "m7_week1",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week1",
    title: "What's the Weather?",
    bigIdeas: ["reasoning"],
    englishFocus: "Weather adjectives + \"It's ___ today.\"",
    koreanL1Note: "\"It's ___\" reuses the copula pattern a third time this year (Month 1 objects, Month 6 animals) — by now expect faster, more confident production.",
    objectives: [
      "I can name four kinds of weather and say \"It's ___ today.\"",
      "I can explain that a weather forecast is really a careful guess, made by finding patterns in a lot of past weather.",
    ],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — forecasting as pattern-based prediction, a second concrete example after Month 1's stars.",
  },
  {
    key: "m7_week2",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week2",
    title: "Hot Weather Clothes or Cold Weather Clothes?",
    bigIdeas: ["perception"],
    englishFocus: "Sorting clothes by weather.",
    koreanL1Note: "Concrete, TPR-friendly theme — pair the sorting game with actual pointing/miming of putting on the clothing sorted.",
    objectives: ["I can sort clothes into 'hot weather' and 'cold weather.'"],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — classification practice, designed to double as a movement break.",
  },
  {
    key: "m7_week3",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week3",
    title: "It's sunny today.",
    bigIdeas: [],
    englishFocus: "Building \"It's ___ today\" sentences tile-by-tile.",
    koreanL1Note: "A second sentence-building pass on this month's copula pattern, this time with weather words instead of nouns.",
    objectives: ["I can build a sentence describing today's weather."],
    standardsNote: "Extends Week 1's weather-forecasting thread into sentence-building practice.",
  },
  {
    key: "m7_week4",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week4",
    title: "It's Sunny Today!",
    bigIdeas: [],
    englishFocus: "\"It's ___ today.\" sentence production.",
    koreanL1Note: "A sentence kids can genuinely check against the real sky outside the classroom window — encourage exactly that.",
    objectives: ["I can say what the weather is like today, in English."],
    standardsNote: "Week 4 speaking-confidence pillar — the most immediately real-world-checkable sentence pattern in the curriculum.",
  },

  // ==================== Month 8 — Travel ====================
  {
    key: "m8_week1",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week1",
    title: "Let's Go!",
    bigIdeas: ["reasoning"],
    englishFocus: "Transportation nouns + \"Let's go by ___.\"",
    koreanL1Note: "\"Let's ___\" is a fixed suggestion chunk with no word-by-word Korean equivalent to build from — teach it whole, the same approach as \"Can I ___?\" in Month 3.",
    objectives: [
      "I can name four ways to travel and say \"Let's go by ___.\"",
      "I can explain that a map app finds the fastest route by trying out many paths and reasoning about which is best.",
    ],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — route-finding as step-by-step reasoning, extending the algorithms thread from the foundations unit.",
  },
  {
    key: "m8_week2",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week2",
    title: "Pack It or Leave It?",
    bigIdeas: ["perception"],
    englishFocus: "Sorting travel items.",
    koreanL1Note: "A concrete, real-suitcase classification loop — what actually needs to come on the trip.",
    objectives: ["I can sort items into 'pack it' and 'leave it.'"],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — classification practice with a genuinely useful real-life sort.",
  },
  {
    key: "m8_week3",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week3",
    title: "Transportation Match",
    bigIdeas: ["learning"],
    englishFocus: "Transportation vocab review inside a flip-card matching game.",
    koreanL1Note: "Third exposure to this month's vocabulary set, recognition/recall practice.",
    objectives: ["I can match transportation words to pictures."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m8_week4",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week4",
    title: "Let's Go by Airplane!",
    bigIdeas: [],
    englishFocus: "\"Let's go by ___.\" sentence production.",
    koreanL1Note: "Encourage kids to pick their favorite, not just the first option — a small but real choice makes the sentence feel truer.",
    objectives: ["I can suggest a way to travel using \"Let's go by ___.\""],
    standardsNote: "Week 4 speaking-confidence pillar.",
  },

  // ==================== Month 9 — My Body ====================
  {
    key: "m9_week1",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week1",
    title: "My Body",
    bigIdeas: ["perception"],
    englishFocus: "Body-part nouns.",
    koreanL1Note: "Pure noun-learning lesson, no new sentence frame — this month's grammar load is deliberately light so the physical/TPR side can carry the lesson.",
    objectives: [
      "I can name six body parts in English.",
      "I can explain that motion-sensor games and fitness trackers use sensors, not eyes, to notice how my body moves.",
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — sensing isn't only \"seeing\"; motion and touch sensors are perception too.",
  },
  {
    key: "m9_week2",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week2",
    title: "Vora Says: Move Your Body!",
    bigIdeas: ["reasoning"],
    englishFocus: "Ordering a body-movement routine.",
    koreanL1Note: "Physical, TPR-heavy lesson — the ordering game becomes a literal Simon-Says-style routine the class performs together.",
    objectives: ["I can order a simple movement routine."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — the most kinesthetic algorithm lesson in the curriculum.",
  },
  {
    key: "m9_week3",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week3",
    title: "Touch your nose.",
    bigIdeas: [],
    englishFocus: "Building a \"touch your ___\" sentence tile-by-tile.",
    koreanL1Note: "Imperative sentence (verb + object only) — simplest sentence shape in the curriculum, paired with real physical movement.",
    objectives: ["I can build and follow a \"touch your ___\" command."],
    standardsNote: "Extends Week 1's body vocabulary into command-sentence practice.",
  },
  {
    key: "m9_week4",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week4",
    title: "Listen Closely: think or sink?",
    bigIdeas: ["perception"],
    englishFocus: "/θ/ (\"th\") vs /s/ minimal-pair listening review.",
    koreanL1Note: "Third quarter-checkpoint review — Korean has no dental fricative /θ/, regularly substituted with /s/ or /t/.",
    objectives: ["I can listen and pick the word I hear: think or sink."],
    standardsNote: "Week 4 pillar, listening-discrimination variant.",
  },

  // ==================== Month 10 — Halloween ====================
  {
    key: "m10_week1",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week1",
    title: "Trick or Treat!",
    bigIdeas: ["learning"],
    englishFocus: "Halloween nouns + \"Trick or treat!\" / \"I'm a ___.\"",
    koreanL1Note: "\"I'm a ___\" (costume) reuses the copula + article pattern from the very first foundations lesson — a nice full-circle callback.",
    objectives: [
      "I can name four Halloween things and say what costume I'm wearing.",
      "I can sort pictures into 'spooky' and 'not spooky,' the same learn-from-examples idea Vora's used all year.",
    ],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — a lighter, seasonal repetition of the classification loop from the foundations unit.",
  },
  {
    key: "m10_week2",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week2",
    title: "Halloween Match-Up",
    bigIdeas: ["learning"],
    englishFocus: "Halloween vocab review inside a flip-card matching game.",
    koreanL1Note: "High-novelty vocabulary set (ghost, witch, bat) makes this a strong week for the matching game specifically — new words benefit most from repeated flip-and-find exposure.",
    objectives: ["I can match Halloween words to pictures."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition of brand-new vocabulary.",
  },
  {
    key: "m10_week3",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week3",
    title: "What Comes Next?",
    bigIdeas: ["reasoning"],
    englishFocus: "Predicting a spooky pattern.",
    koreanL1Note: "Reuses the pattern-prediction mechanic with a seasonal, high-fun theme.",
    objectives: ["I can guess what comes next in a spooky pattern."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — a seasonal, playful pass at pattern-based prediction.",
  },
  {
    key: "m10_week4",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week4",
    title: "I'm a Ghost!",
    bigIdeas: [],
    englishFocus: "\"I'm a ___.\" sentence production (costume).",
    koreanL1Note: "Highest-fun, lowest-stakes speaking week of the year — any silly costume answer is correct as long as the sentence frame is right.",
    objectives: ["I can say \"I'm a ___\" about a costume, real or pretend."],
    standardsNote: "Week 4 speaking-confidence pillar.",
  },

  // ==================== Month 11 — Emotions ====================
  {
    key: "m11_week1",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week1",
    title: "How Do You Feel?",
    bigIdeas: ["natural_interaction", "perception"],
    englishFocus: "Feeling words + \"I feel ___.\"",
    koreanL1Note: "\"I feel ___\" is a new verb pattern (not \"I am ___\") — worth contrasting briefly with the \"It's ___\" pattern used all year so kids don't overgeneralize the copula.",
    objectives: [
      "I can name five feelings and say \"I feel ___.\"",
      "I can explain that an AI can recognize a smiling face, but that's different from truly understanding how someone feels.",
    ],
    standardsNote: "AI4K12 Big Idea 4 (Natural Interaction) — an honest, age-appropriate boundary: recognition vs. understanding, revisited from the foundations unit's \"AI has limits\" thread.",
  },
  {
    key: "m11_week2",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week2",
    title: "I feel happy.",
    bigIdeas: [],
    englishFocus: "Building \"I feel ___\" sentences tile-by-tile.",
    koreanL1Note: "Acting out the feeling before naming it in English lowers the stakes of producing a new verb pattern.",
    objectives: ["I can build an \"I feel ___\" sentence."],
    standardsNote: "Extends Week 1's feelings vocabulary into sentence-building practice.",
  },
  {
    key: "m11_week3",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week3",
    title: "Feelings Match",
    bigIdeas: ["learning"],
    englishFocus: "Matching feeling words to faces.",
    koreanL1Note: "Third exposure to this month's vocabulary set, recognition/recall practice.",
    objectives: ["I can match a feeling word to a face."],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m11_week4",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week4",
    title: "I Feel Happy!",
    bigIdeas: [],
    englishFocus: "\"I feel ___.\" sentence production.",
    koreanL1Note: "Invite an honest answer, not just \"happy\" — this sentence frame is one of the few in the curriculum built for genuine self-expression.",
    objectives: ["I can say how I really feel today, in English."],
    standardsNote: "Week 4 speaking-confidence pillar.",
  },

  // ==================== Month 12 — Winter Holidays (capstone) ====================
  {
    key: "m12_week1",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week1",
    title: "Winter Wonderland",
    bigIdeas: ["societal_impact"],
    englishFocus: "Winter/holiday nouns + \"I want ___ for Christmas.\"",
    koreanL1Note: "\"I want ___\" is a fixed high-frequency chunk kids will hear constantly this season — a natural, motivating place to end the year's grammar work.",
    objectives: [
      "I can name five winter/holiday things and say what I want.",
      "I can name one AI helper from this year and explain what it does.",
    ],
    standardsNote: "AI4K12 Big Idea 5 (Societal Impact) — a light capstone question that has kids recall any AI example from the whole year, not just this month's.",
  },
  {
    key: "m12_week2",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week2",
    title: "Review Sort",
    bigIdeas: ["perception", "learning"],
    englishFocus: "A cumulative sorting game using vocabulary from across the year.",
    koreanL1Note: "Pulls vocabulary from several earlier months — a real formative check on whether words stuck beyond the month they were taught in.",
    objectives: ["I can sort a mix of words from across the year into two categories."],
    standardsNote: "AI4K12 Big Idea 1 (Perception) & Big Idea 3 (Learning) — the year's cumulative classification review, mirroring the foundations unit's Week 8 Review Carnival.",
  },
  {
    key: "m12_week3",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week3",
    title: "A Year of Patterns",
    bigIdeas: ["reasoning"],
    englishFocus: "A cumulative pattern game mixing images from across the year.",
    koreanL1Note: "A celebratory review of the pattern-prediction mechanic used in Months 1, 4, 6, and 10.",
    objectives: ["I can guess what comes next in a pattern using pictures from across the year."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — the year's cumulative reasoning review.",
  },
  {
    key: "m12_week4",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week4",
    title: "Listen Closely: van or ban?",
    bigIdeas: ["perception"],
    englishFocus: "/v/ vs /b/ minimal-pair listening review (bonus fifth Korean L1 gap).",
    koreanL1Note: "Korean has no /v/ phoneme; it's regularly approximated with /b/ — a fifth high-value listening contrast to close out the year alongside r/l, f/p, and th/s. See docs/KOREAN_L1_NOTES.md.",
    objectives: ["I can listen and pick the word I hear: van or ban."],
    standardsNote: "Week 4 pillar, listening-discrimination variant — the year's final checkpoint.",
  },
];

export function getMonthlyLessonMeta(key: string): LessonMeta | undefined {
  return MONTHLY_SCOPE_AND_SEQUENCE.find((l) => l.key === key);
}

const SLOT_ORDER: Record<string, number> = { week1: 0, week2: 1, week3: 2, week4: 3 };

export function lessonsForMonth(monthIndex: number): LessonMeta[] {
  return MONTHLY_SCOPE_AND_SEQUENCE.filter((l) => l.monthIndex === monthIndex).sort(
    (a, b) => SLOT_ORDER[a.slot ?? "week1"] - SLOT_ORDER[b.slot ?? "week1"]
  );
}
