import type { LessonMeta } from "./types";

/**
 * The lesson-level map for the 12-month themed curriculum (see
 * lib/curriculum/months.ts). Every month has exactly FOUR lessons, one per
 * week — a standalone, full class plan each, matching a once-a-week class
 * cadence rather than a single monthly "unit":
 *
 * - `week1` — introduces the month's vocabulary, sentence pattern, and AI
 *   big idea through Vora.
 * - `week2` / `week3` — each builds a full lesson (its own light vocab
 *   recap, a short concept reinforcement, one game, a formative check)
 *   around one of the month's two games, so playing is still teaching, not
 *   just playing.
 * - `week4` — speaking-confidence + review week (a sentence/chant
 *   production task, or a quarter-checkpoint listening review).
 *
 * See lib/curriculum/lessons/month1.ts..month12.ts for the full authored
 * segment content, and docs/MONTHLY_CURRICULUM.md for the teacher-facing
 * map this mirrors.
 */
export const MONTHLY_SCOPE_AND_SEQUENCE: LessonMeta[] = [
  // ==================== Month 1 — Space ====================
  {
    key: "m1_week1",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week1",
    title: { en: "It's a Star!", ko: "별이에요!" },
    bigIdeas: ["reasoning", "learning"],
    englishFocus: { en: "Space nouns + \"It's a ___.\"", ko: "우주 명사와 \"It's a ___.\" 문장" },
    koreanL1Note:
      "\"It's a ___\" reuses the copula pattern from the foundations unit (Week 1) — a good check for whether that structure stuck, now with brand-new vocabulary.",
    objectives: [
      { en: "I can name five things in space.", ko: "나는 우주에 있는 것 다섯 가지를 말할 수 있어요." },
      { en: "I can explain that Vora finds patterns in pictures of stars, the same way it sorts other pictures.", ko: "나는 보라가 다른 그림을 분류하듯 별 사진에서도 패턴을 찾는다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — pattern-finding in images, introduced with space as the concrete example.",
  },
  {
    key: "m1_week2",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week2",
    title: { en: "Space Thing or Earth Thing?", ko: "우주 물건일까요, 지구 물건일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Space vocab review inside a sort-the-picture game.", ko: "그림 분류 게임으로 우주 어휘 복습" },
    koreanL1Note: "Same vocabulary as Week 1, new mechanic — repetition across a different interaction is the goal, not new grammar.",
    objectives: [{ en: "I can sort pictures into 'space thing' and 'earth thing,' and check Vora's guesses.", ko: "나는 그림을 '우주 물건'과 '지구 물건'으로 분류하고 로비의 추측을 확인할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — a second, playful pass at the classification loop from Week 1.",
  },
  {
    key: "m1_week3",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week3",
    title: { en: "Space Word Match", ko: "우주 단어 짝 맞추기" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Space vocab review inside a flip-card matching game.", ko: "짝 맞추기 게임으로 우주 어휘 복습" },
    koreanL1Note: "Third exposure to this month's vocabulary set — recognition/recall practice complements Week 1's production practice.",
    objectives: [{ en: "I can find matching space word-picture pairs.", ko: "나는 우주 단어와 그림 짝을 찾을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure is literally how both kids and Vora get better at recognizing something.",
  },
  {
    key: "m1_week4",
    unitKey: "m1_space",
    monthIndex: 1,
    slot: "week4",
    title: { en: "I See a Rocket!", ko: "로켓이 보여요!" },
    bigIdeas: [],
    englishFocus: { en: "\"I see a ___.\" sentence production.", ko: "\"I see a ___.\" 문장 만들기" },
    koreanL1Note: "First production (not just recognition) of a full 3-word sentence with this month's nouns — build it tile-by-tile before asking for free speech.",
    objectives: [{ en: "I can say \"I see a ___\" about a space picture.", ko: "나는 우주 그림을 보고 \"I see a ___\"라고 말할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar — short, low-stakes, one sentence pattern produced out loud by every child.",
  },

  // ==================== Month 2 — Culture & Countries ====================
  {
    key: "m2_week1",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week1",
    title: { en: "Hello, World!", ko: "안녕, 세계!" },
    bigIdeas: ["societal_impact"],
    englishFocus: { en: "Country/food/dance nouns + \"I'm from ___.\"", ko: "나라·음식·춤 명사와 \"I'm from ___.\" 문장" },
    koreanL1Note: "\"I'm from Korea\" gives kids a sentence about themselves that's true and easy to be proud of — start here before other countries.",
    objectives: [
      { en: "I can name three countries and say \"I'm from ___.\"", ko: "나는 나라 세 곳의 이름을 말하고 \"I'm from ___.\"라고 말할 수 있어요." },
      { en: "I can explain that translator apps use AI to help people who speak different languages understand each other.", ko: "나는 번역 앱이 AI를 이용해 서로 다른 언어를 쓰는 사람들이 이해하도록 돕는다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 5 (Societal Impact) — machine translation as a concrete, kid-relatable example of AI's real-world reach.",
  },
  {
    key: "m2_week2",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week2",
    title: { en: "A Pretend Trip", ko: "가상 여행" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Ordering a travel routine.", ko: "여행 루틴 순서 배열" },
    koreanL1Note: "Sequencing words (first/next/then/last) get reused from the foundations unit inside a brand-new routine — a good transfer check.",
    objectives: [{ en: "I can order the steps of a pretend trip.", ko: "나는 가상 여행의 순서를 배열할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — ordered steps as a concrete algorithm, transferred to a new routine.",
  },
  {
    key: "m2_week3",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week3",
    title: { en: "World Word Match", ko: "세계 단어 짝 맞추기" },
    bigIdeas: ["learning"],
    englishFocus: { en: "World vocab review inside a flip-card matching game.", ko: "짝 맞추기 게임으로 세계 어휘 복습" },
    koreanL1Note: "Third exposure to this month's vocabulary, recognition/recall practice after Week 1's production and Week 2's sequencing.",
    objectives: [{ en: "I can match world vocabulary to pictures.", ko: "나는 세계 어휘를 그림과 짝지을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m2_week4",
    unitKey: "m2_culture",
    monthIndex: 2,
    slot: "week4",
    title: { en: "I'm from Korea!", ko: "저는 한국에서 왔어요!" },
    bigIdeas: [],
    englishFocus: { en: "\"I'm from ___.\" sentence production.", ko: "\"I'm from ___.\" 문장 만들기" },
    koreanL1Note: "Contraction practice (\"I'm\" = \"I am\") — Korean has no equivalent contraction, model it as one chunk, not two words squeezed together.",
    objectives: [{ en: "I can say \"I'm from Korea\" with confidence.", ko: "나는 자신 있게 \"I'm from Korea\"라고 말할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar — a sentence every child can say truthfully about themselves.",
  },

  // ==================== Month 3 — Friends ====================
  {
    key: "m3_week1",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week1",
    title: { en: "Making a Friend", ko: "친구 사귀기" },
    bigIdeas: ["natural_interaction"],
    englishFocus: { en: "Friendship phrases + \"Can I play?\" / \"Let's share.\"", ko: "우정 표현과 \"Can I play?\" / \"Let's share.\"" },
    koreanL1Note: "\"Can I ___?\" fronts an auxiliary the same way \"Do you ___?\" did in the foundations unit — call out the pattern explicitly so it transfers.",
    objectives: [
      { en: "I can ask \"Can I play?\" and offer to share.", ko: "나는 \"Can I play?\"라고 묻고 나눠 쓰자고 제안할 수 있어요." },
      { en: "I can explain that a voice assistant listens for me to stop talking before it answers, like a good friend takes turns.", ko: "나는 음성 비서가 좋은 친구처럼 내가 말을 멈출 때까지 기다렸다가 대답한다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 4 (Natural Interaction) — turn-taking in conversation, framed through friendship rather than technology first.",
  },
  {
    key: "m3_week2",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week2",
    title: { en: "Can I play?", ko: "같이 놀아도 될까요?" },
    bigIdeas: [],
    englishFocus: { en: "Building the \"Can I play?\" sentence tile-by-tile.", ko: "\"Can I play?\" 문장을 한 조각씩 만들기" },
    koreanL1Note: "Reinforces \"Can I play?\" as a fixed chunk kids can produce quickly, now built word-by-word so the word order is visible.",
    objectives: [{ en: "I can build the sentence \"Can I play?\" in the right word order.", ko: "나는 \"Can I play?\"를 올바른 어순으로 만들 수 있어요." }],
    standardsNote: "Extends Week 1's natural-interaction thread into English word-order practice.",
  },
  {
    key: "m3_week3",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week3",
    title: { en: "Feelings Match", ko: "감정 짝 맞추기" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Matching feeling words to faces.", ko: "감정 단어를 표정과 짝짓기" },
    koreanL1Note: "New, smaller vocabulary set (happy/sad/kind) previewing Month 11's Emotions theme — light exposure now, full unit later.",
    objectives: [{ en: "I can match a feeling word to a face.", ko: "나는 감정 단어를 표정과 짝지을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — recognition practice through repeated matching.",
  },
  {
    key: "m3_week4",
    unitKey: "m3_friends",
    monthIndex: 3,
    slot: "week4",
    title: { en: "Listen Closely: light or right?", ko: "잘 들어보세요: light일까요, right일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/r/ vs /l/ minimal-pair listening review.", ko: "/r/와 /l/ 최소 대립쌍 듣기 복습" },
    koreanL1Note: "Quarter-checkpoint review of the single highest-frequency Korean-learner sound gap (see docs/KOREAN_L1_NOTES.md) — spaced repetition from the foundations unit.",
    objectives: [{ en: "I can listen and pick the word I hear: light or right.", ko: "나는 듣고 들은 단어를 고를 수 있어요: light 또는 right." }],
    standardsNote: "Week 4 pillar, listening-discrimination variant — every third month reviews one of the four core Korean L1 sound gaps.",
  },

  // ==================== Month 4 — Environment ====================
  {
    key: "m4_week1",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week1",
    title: { en: "Take Care of Earth", ko: "지구를 돌봐요" },
    bigIdeas: ["learning", "societal_impact"],
    englishFocus: { en: "Nature nouns + \"We should / shouldn't ___.\"", ko: "자연 명사와 \"We should / shouldn't ___.\" 표현" },
    koreanL1Note: "Modal \"should\" has no verb-final counterpart to lean on, same challenge as \"can\" in the foundations unit — model as a fixed chunk first.",
    objectives: [
      { en: "I can say one thing we should do and one thing we shouldn't do for the earth.", ko: "나는 지구를 위해 해야 할 일과 하지 말아야 할 일을 각각 한 가지씩 말할 수 있어요." },
      { en: "I can explain that AI helps scientists learn about our climate by studying huge amounts of weather data.", ko: "나는 AI가 방대한 날씨 데이터를 연구해 과학자들이 기후를 이해하도록 돕는다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — learning from large datasets, introduced through climate science.",
  },
  {
    key: "m4_week2",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week2",
    title: { en: "Recycling Steps", ko: "재활용 순서" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Ordering the steps of recycling.", ko: "재활용 순서 배열" },
    koreanL1Note: "Reinforces first/next/then/last from the foundations unit inside a new, real-world routine.",
    objectives: [{ en: "I can put the steps of recycling in the right order.", ko: "나는 재활용 순서를 올바르게 배열할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — an algorithm is an exact, ordered list of steps.",
  },
  {
    key: "m4_week3",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week3",
    title: { en: "What Comes Next?", ko: "다음은 무엇일까요?" },
    bigIdeas: ["reasoning", "learning"],
    englishFocus: { en: "Predicting a simple growth pattern.", ko: "간단한 성장 패턴 예측하기" },
    koreanL1Note: "Reuses the pattern-prediction mechanic first introduced in Month 1 — a good transfer check across a very different theme.",
    objectives: [{ en: "I can guess what comes next in a pattern.", ko: "나는 패턴에서 다음에 올 것을 추측할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — a second, playful pass at pattern-based prediction.",
  },
  {
    key: "m4_week4",
    unitKey: "m4_environment",
    monthIndex: 4,
    slot: "week4",
    title: { en: "We Should Recycle!", ko: "우리는 재활용해야 해요!" },
    bigIdeas: [],
    englishFocus: { en: "\"We should ___.\" sentence production.", ko: "\"We should ___.\" 문장 만들기" },
    koreanL1Note: "First group-subject sentence (\"we,\" not \"I\") — a small but genuine shift kids should hear called out.",
    objectives: [{ en: "I can say one thing \"we should\" do for the earth.", ko: "나는 지구를 위해 \"we should\" 해야 할 일을 한 가지 말할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar — closes the environment theme on a sentence kids can repeat at home.",
  },

  // ==================== Month 5 — Family ====================
  {
    key: "m5_week1",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week1",
    title: { en: "This Is My Family", ko: "우리 가족이에요" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Family nouns + \"This is my ___.\"", ko: "가족 명사와 \"This is my ___.\" 문장" },
    koreanL1Note: "Korean family terms encode relative age/side of family with no single English equivalent — validate kids who want more precision than 'brother/sister' gives them, don't correct it away.",
    objectives: [
      { en: "I can introduce four family members in English.", ko: "나는 영어로 가족 네 명을 소개할 수 있어요." },
      { en: "I can explain that face-recognition apps sometimes mix up people who look alike, unlike how I always know my own family.", ko: "나는 얼굴 인식 앱이 닮은 사람을 가끔 헷갈려 하지만, 나는 우리 가족을 항상 알아본다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — the limits of computer vision, made concrete and reassuring rather than scary.",
  },
  {
    key: "m5_week2",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week2",
    title: { en: "This is my brother.", ko: "제 형/오빠/남동생이에요." },
    bigIdeas: [],
    englishFocus: { en: "Building \"This is my ___\" sentences tile-by-tile.", ko: "\"This is my ___\" 문장을 한 조각씩 만들기" },
    koreanL1Note: "Repeats the possessive \"my\" from the foundations unit's classroom-objects lesson, now with people instead of things.",
    objectives: [{ en: "I can build a sentence introducing a family member.", ko: "나는 가족을 소개하는 문장을 만들 수 있어요." }],
    standardsNote: "Extends Week 1's family vocabulary into sentence-building practice.",
  },
  {
    key: "m5_week3",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week3",
    title: { en: "Family Word or School Word?", ko: "가족 단어일까요, 학교 단어일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Sorting family words vs. school words.", ko: "가족 단어와 학교 단어 분류하기" },
    koreanL1Note: "A gentle classification loop, distinguishing this month's vocabulary from an already-known category (school, from the foundations unit).",
    objectives: [{ en: "I can sort words into 'family' and 'school,' and check Vora's guesses.", ko: "나는 단어를 '가족'과 '학교'로 분류하고 보라의 추측을 확인할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — classification practice against a contrasting, already-familiar category.",
  },
  {
    key: "m5_week4",
    unitKey: "m5_family",
    monthIndex: 5,
    slot: "week4",
    title: { en: "This Is My Sister!", ko: "제 여동생이에요!" },
    bigIdeas: [],
    englishFocus: { en: "\"This is my ___.\" sentence production.", ko: "\"This is my ___.\" 문장 만들기" },
    koreanL1Note: "Kids may want to name a cousin, grandparent, or pet — welcome any real family member, the sentence frame is what matters.",
    objectives: [{ en: "I can proudly introduce one real family member in English.", ko: "나는 진짜 가족 중 한 명을 영어로 자신 있게 소개할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar — personal, low-stakes production about something every child has an honest answer for.",
  },

  // ==================== Month 6 — Animals ====================
  {
    key: "m6_week1",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week1",
    title: { en: "Wild Animals", ko: "야생 동물" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Wild animal nouns + \"It's a big / small ___.\"", ko: "야생 동물 명사와 \"It's a big / small ___.\" 문장" },
    koreanL1Note: "Adjective-before-noun order (\"a big lion\") matches Korean word order — call this out as an easy win, not everything is a hard shift.",
    objectives: [
      { en: "I can name five wild animals and describe them as big or small.", ko: "나는 야생 동물 다섯 가지의 이름을 말하고 크기를 설명할 수 있어요." },
      { en: "I can explain that wildlife cameras use AI to recognize which animal walked by, the same sorting idea as Vora's games.", ko: "나는 야생동물 카메라가 AI로 지나간 동물을 알아낸다는 것을, 보라의 분류 게임과 같은 원리로 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — a real deployed use of image classification kids can picture concretely (a camera trap in a forest).",
  },
  {
    key: "m6_week2",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week2",
    title: { en: "What Comes Next?", ko: "다음은 무엇일까요?" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Predicting an animal pattern.", ko: "동물 패턴 예측하기" },
    koreanL1Note: "Pattern words like \"same/different\" carry over from the foundations unit's colors-and-patterns week.",
    objectives: [{ en: "I can guess what comes next in an animal pattern.", ko: "나는 동물 패턴에서 다음에 올 것을 추측할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — a playful reintroduction of pattern-based prediction.",
  },
  {
    key: "m6_week3",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week3",
    title: { en: "Animal Words", ko: "동물 단어" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Animal vocab review inside a flip-card matching game.", ko: "짝 맞추기 게임으로 동물 어휘 복습" },
    koreanL1Note: "Third exposure to this month's vocabulary set — recognition/recall practice.",
    objectives: [{ en: "I can match animal words to pictures.", ko: "나는 동물 단어를 그림과 짝지을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m6_week4",
    unitKey: "m6_animals",
    monthIndex: 6,
    slot: "week4",
    title: { en: "Listen Closely: fan or pan?", ko: "잘 들어보세요: fan일까요, pan일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/f/ vs /p/ minimal-pair listening review.", ko: "/f/와 /p/ 최소 대립쌍 듣기 복습" },
    koreanL1Note: "Second quarter-checkpoint review — Korean has no /f/ phoneme, so this contrast is genuinely new, not just underused, and benefits from repeated exposure across the year.",
    objectives: [{ en: "I can listen and pick the word I hear: fan or pan.", ko: "나는 듣고 들은 단어를 고를 수 있어요: fan 또는 pan." }],
    standardsNote: "Week 4 pillar, listening-discrimination variant.",
  },

  // ==================== Month 7 — Weather ====================
  {
    key: "m7_week1",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week1",
    title: { en: "What's the Weather?", ko: "오늘 날씨는 어때요?" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Weather adjectives + \"It's ___ today.\"", ko: "날씨 형용사와 \"It's ___ today.\" 문장" },
    koreanL1Note: "\"It's ___\" reuses the copula pattern a third time this year (Month 1 objects, Month 6 animals) — by now expect faster, more confident production.",
    objectives: [
      { en: "I can name four kinds of weather and say \"It's ___ today.\"", ko: "나는 날씨 네 가지의 이름을 말하고 \"It's ___ today.\"라고 말할 수 있어요." },
      { en: "I can explain that a weather forecast is really a careful guess, made by finding patterns in a lot of past weather.", ko: "나는 일기예보가 사실은 과거 날씨의 패턴을 바탕으로 한 신중한 추측이라는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — forecasting as pattern-based prediction, a second concrete example after Month 1's stars.",
  },
  {
    key: "m7_week2",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week2",
    title: { en: "Hot Weather Clothes or Cold Weather Clothes?", ko: "더운 날씨 옷일까요, 추운 날씨 옷일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Sorting clothes by weather.", ko: "날씨에 맞는 옷 분류하기" },
    koreanL1Note: "Concrete, TPR-friendly theme — pair the sorting game with actual pointing/miming of putting on the clothing sorted.",
    objectives: [{ en: "I can sort clothes into 'hot weather' and 'cold weather.'", ko: "나는 옷을 '더운 날씨'와 '추운 날씨'로 분류할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — classification practice, designed to double as a movement break.",
  },
  {
    key: "m7_week3",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week3",
    title: { en: "It's sunny today.", ko: "오늘은 맑아요." },
    bigIdeas: [],
    englishFocus: { en: "Building \"It's ___ today\" sentences tile-by-tile.", ko: "\"It's ___ today\" 문장을 한 조각씩 만들기" },
    koreanL1Note: "A second sentence-building pass on this month's copula pattern, this time with weather words instead of nouns.",
    objectives: [{ en: "I can build a sentence describing today's weather.", ko: "나는 오늘 날씨를 설명하는 문장을 만들 수 있어요." }],
    standardsNote: "Extends Week 1's weather-forecasting thread into sentence-building practice.",
  },
  {
    key: "m7_week4",
    unitKey: "m7_weather",
    monthIndex: 7,
    slot: "week4",
    title: { en: "It's Sunny Today!", ko: "오늘은 맑아요!" },
    bigIdeas: [],
    englishFocus: { en: "\"It's ___ today.\" sentence production.", ko: "\"It's ___ today.\" 문장 만들기" },
    koreanL1Note: "A sentence kids can genuinely check against the real sky outside the classroom window — encourage exactly that.",
    objectives: [{ en: "I can say what the weather is like today, in English.", ko: "나는 오늘 날씨가 어떤지 영어로 말할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar — the most immediately real-world-checkable sentence pattern in the curriculum.",
  },

  // ==================== Month 8 — Travel ====================
  {
    key: "m8_week1",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week1",
    title: { en: "Let's Go!", ko: "출발해요!" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Transportation nouns + \"Let's go by ___.\"", ko: "탈것 명사와 \"Let's go by ___.\" 문장" },
    koreanL1Note: "\"Let's ___\" is a fixed suggestion chunk with no word-by-word Korean equivalent to build from — teach it whole, the same approach as \"Can I ___?\" in Month 3.",
    objectives: [
      { en: "I can name four ways to travel and say \"Let's go by ___.\"", ko: "나는 이동 수단 네 가지의 이름을 말하고 \"Let's go by ___.\"라고 말할 수 있어요." },
      { en: "I can explain that a map app finds the fastest route by trying out many paths and reasoning about which is best.", ko: "나는 지도 앱이 여러 경로를 시도해 보고 가장 좋은 길을 추론해 찾는다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — route-finding as step-by-step reasoning, extending the algorithms thread from the foundations unit.",
  },
  {
    key: "m8_week2",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week2",
    title: { en: "Pack It or Leave It?", ko: "챙길까요, 두고 갈까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Sorting travel items.", ko: "여행 물건 분류하기" },
    koreanL1Note: "A concrete, real-suitcase classification loop — what actually needs to come on the trip.",
    objectives: [{ en: "I can sort items into 'pack it' and 'leave it.'", ko: "나는 물건을 '챙길 것'과 '두고 갈 것'으로 분류할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — classification practice with a genuinely useful real-life sort.",
  },
  {
    key: "m8_week3",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week3",
    title: { en: "Transportation Match", ko: "탈것 짝 맞추기" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Transportation vocab review inside a flip-card matching game.", ko: "짝 맞추기 게임으로 탈것 어휘 복습" },
    koreanL1Note: "Third exposure to this month's vocabulary set, recognition/recall practice.",
    objectives: [{ en: "I can match transportation words to pictures.", ko: "나는 탈것 단어를 그림과 짝지을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m8_week4",
    unitKey: "m8_travel",
    monthIndex: 8,
    slot: "week4",
    title: { en: "Let's Go by Airplane!", ko: "비행기를 타고 가요!" },
    bigIdeas: [],
    englishFocus: { en: "\"Let's go by ___.\" sentence production.", ko: "\"Let's go by ___.\" 문장 만들기" },
    koreanL1Note: "Encourage kids to pick their favorite, not just the first option — a small but real choice makes the sentence feel truer.",
    objectives: [{ en: "I can suggest a way to travel using \"Let's go by ___.\"", ko: "나는 \"Let's go by ___.\"를 사용해 이동 방법을 제안할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar.",
  },

  // ==================== Month 9 — My Body ====================
  {
    key: "m9_week1",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week1",
    title: { en: "My Body", ko: "내 몸" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Body-part nouns.", ko: "신체 부위 명사" },
    koreanL1Note: "Pure noun-learning lesson, no new sentence frame — this month's grammar load is deliberately light so the physical/TPR side can carry the lesson.",
    objectives: [
      { en: "I can name six body parts in English.", ko: "나는 영어로 신체 부위 여섯 가지를 말할 수 있어요." },
      { en: "I can explain that motion-sensor games and fitness trackers use sensors, not eyes, to notice how my body moves.", ko: "나는 동작 인식 게임과 활동량 측정기가 눈이 아니라 센서로 내 몸의 움직임을 감지한다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) — sensing isn't only \"seeing\"; motion and touch sensors are perception too.",
  },
  {
    key: "m9_week2",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week2",
    title: { en: "Vora Says: Move Your Body!", ko: "보라 가라사대: 몸을 움직여요!" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Ordering a body-movement routine.", ko: "몸동작 순서 배열" },
    koreanL1Note: "Physical, TPR-heavy lesson — the ordering game becomes a literal Simon-Says-style routine the class performs together.",
    objectives: [{ en: "I can order a simple movement routine.", ko: "나는 간단한 동작 순서를 배열할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — the most kinesthetic algorithm lesson in the curriculum.",
  },
  {
    key: "m9_week3",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week3",
    title: { en: "Touch your nose.", ko: "코를 만지세요." },
    bigIdeas: [],
    englishFocus: { en: "Building a \"touch your ___\" sentence tile-by-tile.", ko: "\"touch your ___\" 문장을 한 조각씩 만들기" },
    koreanL1Note: "Imperative sentence (verb + object only) — simplest sentence shape in the curriculum, paired with real physical movement.",
    objectives: [{ en: "I can build and follow a \"touch your ___\" command.", ko: "나는 \"touch your ___\" 명령문을 만들고 따를 수 있어요." }],
    standardsNote: "Extends Week 1's body vocabulary into command-sentence practice.",
  },
  {
    key: "m9_week4",
    unitKey: "m9_body",
    monthIndex: 9,
    slot: "week4",
    title: { en: "Listen Closely: think or sink?", ko: "잘 들어보세요: think일까요, sink일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/θ/ (\"th\") vs /s/ minimal-pair listening review.", ko: "/θ/(th)와 /s/ 최소 대립쌍 듣기 복습" },
    koreanL1Note: "Third quarter-checkpoint review — Korean has no dental fricative /θ/, regularly substituted with /s/ or /t/.",
    objectives: [{ en: "I can listen and pick the word I hear: think or sink.", ko: "나는 듣고 들은 단어를 고를 수 있어요: think 또는 sink." }],
    standardsNote: "Week 4 pillar, listening-discrimination variant.",
  },

  // ==================== Month 10 — Halloween ====================
  {
    key: "m10_week1",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week1",
    title: { en: "Trick or Treat!", ko: "트릭 오어 트릿!" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Halloween nouns + \"Trick or treat!\" / \"I'm a ___.\"", ko: "할로윈 명사와 \"Trick or treat!\" / \"I'm a ___.\" 표현" },
    koreanL1Note: "\"I'm a ___\" (costume) reuses the copula + article pattern from the very first foundations lesson — a nice full-circle callback.",
    objectives: [
      { en: "I can name four Halloween things and say what costume I'm wearing.", ko: "나는 할로윈 관련 사물 네 가지를 말하고 내가 입은 코스튬을 말할 수 있어요." },
      { en: "I can sort pictures into 'spooky' and 'not spooky,' the same learn-from-examples idea Vora's used all year.", ko: "나는 그림을 '무서운 것'과 '무섭지 않은 것'으로 분류할 수 있어요 — 보라가 1년 내내 사용한 '예시로 배우기'와 같은 방식이에요." },
    ],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — a lighter, seasonal repetition of the classification loop from the foundations unit.",
  },
  {
    key: "m10_week2",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week2",
    title: { en: "Halloween Match-Up", ko: "할로윈 짝 맞추기" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Halloween vocab review inside a flip-card matching game.", ko: "짝 맞추기 게임으로 할로윈 어휘 복습" },
    koreanL1Note: "High-novelty vocabulary set (ghost, witch, bat) makes this a strong week for the matching game specifically — new words benefit most from repeated flip-and-find exposure.",
    objectives: [{ en: "I can match Halloween words to pictures.", ko: "나는 할로윈 단어를 그림과 짝지을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition of brand-new vocabulary.",
  },
  {
    key: "m10_week3",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week3",
    title: { en: "What Comes Next?", ko: "다음엔 뭐가 올까요?" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Predicting a spooky pattern.", ko: "무서운 패턴 예측하기" },
    koreanL1Note: "Reuses the pattern-prediction mechanic with a seasonal, high-fun theme.",
    objectives: [{ en: "I can guess what comes next in a spooky pattern.", ko: "나는 무서운 패턴에서 다음에 올 것을 추측할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — a seasonal, playful pass at pattern-based prediction.",
  },
  {
    key: "m10_week4",
    unitKey: "m10_halloween",
    monthIndex: 10,
    slot: "week4",
    title: { en: "I'm a Ghost!", ko: "저는 유령이에요!" },
    bigIdeas: [],
    englishFocus: { en: "\"I'm a ___.\" sentence production (costume).", ko: "\"I'm a ___.\" 문장 만들기 (코스튬)" },
    koreanL1Note: "Highest-fun, lowest-stakes speaking week of the year — any silly costume answer is correct as long as the sentence frame is right.",
    objectives: [{ en: "I can say \"I'm a ___\" about a costume, real or pretend.", ko: "나는 진짜든 상상이든 코스튬에 대해 \"I'm a ___\"라고 말할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar.",
  },

  // ==================== Month 11 — Emotions ====================
  {
    key: "m11_week1",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week1",
    title: { en: "How Do You Feel?", ko: "기분이 어때요?" },
    bigIdeas: ["natural_interaction", "perception"],
    englishFocus: { en: "Feeling words + \"I feel ___.\"", ko: "감정 단어와 \"I feel ___.\" 문장" },
    koreanL1Note: "\"I feel ___\" is a new verb pattern (not \"I am ___\") — worth contrasting briefly with the \"It's ___\" pattern used all year so kids don't overgeneralize the copula.",
    objectives: [
      { en: "I can name five feelings and say \"I feel ___.\"", ko: "나는 감정 다섯 가지의 이름을 말하고 \"I feel ___.\"라고 말할 수 있어요." },
      { en: "I can explain that an AI can recognize a smiling face, but that's different from truly understanding how someone feels.", ko: "나는 AI가 웃는 얼굴을 인식할 수는 있지만, 그것이 누군가의 진짜 기분을 이해하는 것과는 다르다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 4 (Natural Interaction) — an honest, age-appropriate boundary: recognition vs. understanding, revisited from the foundations unit's \"AI has limits\" thread.",
  },
  {
    key: "m11_week2",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week2",
    title: { en: "I feel happy.", ko: "저는 행복해요." },
    bigIdeas: [],
    englishFocus: { en: "Building \"I feel ___\" sentences tile-by-tile.", ko: "\"I feel ___\" 문장을 한 조각씩 만들기" },
    koreanL1Note: "Acting out the feeling before naming it in English lowers the stakes of producing a new verb pattern.",
    objectives: [{ en: "I can build an \"I feel ___\" sentence.", ko: "나는 \"I feel ___\" 문장을 만들 수 있어요." }],
    standardsNote: "Extends Week 1's feelings vocabulary into sentence-building practice.",
  },
  {
    key: "m11_week3",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week3",
    title: { en: "Feelings Match", ko: "감정 짝 맞추기" },
    bigIdeas: ["learning"],
    englishFocus: { en: "Matching feeling words to faces.", ko: "감정 단어를 표정과 짝짓기" },
    koreanL1Note: "Third exposure to this month's vocabulary set, recognition/recall practice.",
    objectives: [{ en: "I can match a feeling word to a face.", ko: "나는 감정 단어를 표정과 짝지을 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — repeated exposure to build recognition.",
  },
  {
    key: "m11_week4",
    unitKey: "m11_emotions",
    monthIndex: 11,
    slot: "week4",
    title: { en: "I Feel Happy!", ko: "저는 행복해요!" },
    bigIdeas: [],
    englishFocus: { en: "\"I feel ___.\" sentence production.", ko: "\"I feel ___.\" 문장 만들기" },
    koreanL1Note: "Invite an honest answer, not just \"happy\" — this sentence frame is one of the few in the curriculum built for genuine self-expression.",
    objectives: [{ en: "I can say how I really feel today, in English.", ko: "나는 오늘 진짜 기분이 어떤지 영어로 말할 수 있어요." }],
    standardsNote: "Week 4 speaking-confidence pillar.",
  },

  // ==================== Month 12 — Winter Holidays (capstone) ====================
  {
    key: "m12_week1",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week1",
    title: { en: "Winter Wonderland", ko: "겨울 나라" },
    bigIdeas: ["societal_impact"],
    englishFocus: { en: "Winter/holiday nouns + \"I want ___ for Christmas.\"", ko: "겨울·크리스마스 명사와 \"I want ___ for Christmas.\" 문장" },
    koreanL1Note: "\"I want ___\" is a fixed high-frequency chunk kids will hear constantly this season — a natural, motivating place to end the year's grammar work.",
    objectives: [
      { en: "I can name five winter/holiday things and say what I want.", ko: "나는 겨울·크리스마스 관련 사물 다섯 가지를 말하고 원하는 것을 말할 수 있어요." },
      { en: "I can name one AI helper from this year and explain what it does.", ko: "나는 올해 배운 AI 도우미를 한 가지 말하고 그것이 하는 일을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 5 (Societal Impact) — a light capstone question that has kids recall any AI example from the whole year, not just this month's.",
  },
  {
    key: "m12_week2",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week2",
    title: { en: "Review Sort", ko: "복습 분류" },
    bigIdeas: ["perception", "learning"],
    englishFocus: { en: "A cumulative sorting game using vocabulary from across the year.", ko: "1년 동안 배운 어휘로 하는 종합 분류 게임" },
    koreanL1Note: "Pulls vocabulary from several earlier months — a real formative check on whether words stuck beyond the month they were taught in.",
    objectives: [{ en: "I can sort a mix of words from across the year into two categories.", ko: "나는 1년 동안 배운 여러 단어를 두 가지로 분류할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 1 (Perception) & Big Idea 3 (Learning) — the year's cumulative classification review, mirroring the foundations unit's Week 8 Review Carnival.",
  },
  {
    key: "m12_week3",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week3",
    title: { en: "A Year of Patterns", ko: "1년의 패턴" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "A cumulative pattern game mixing images from across the year.", ko: "1년 동안의 이미지를 섞은 종합 패턴 게임" },
    koreanL1Note: "A celebratory review of the pattern-prediction mechanic used in Months 1, 4, 6, and 10.",
    objectives: [{ en: "I can guess what comes next in a pattern using pictures from across the year.", ko: "나는 1년 동안 배운 그림으로 패턴에서 다음에 올 것을 추측할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — the year's cumulative reasoning review.",
  },
  {
    key: "m12_week4",
    unitKey: "m12_winter",
    monthIndex: 12,
    slot: "week4",
    title: { en: "Listen Closely: van or ban?", ko: "잘 들어보세요: van일까요, ban일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/v/ vs /b/ minimal-pair listening review (bonus fifth Korean L1 gap).", ko: "/v/와 /b/ 최소 대립쌍 듣기 (다섯 번째 발음 격차)" },
    koreanL1Note: "Korean has no /v/ phoneme; it's regularly approximated with /b/ (ㅂ) — a fifth high-value listening contrast to close out the year alongside r/l, f/p, and th/s. See docs/KOREAN_L1_NOTES.md.",
    objectives: [{ en: "I can listen and pick the word I hear: van or ban.", ko: "나는 듣고 들은 단어를 고를 수 있어요: van 또는 ban." }],
    standardsNote: "Week 4 pillar, listening-discrimination variant — the year's final checkpoint.",
  },
];

export function getMonthlyLessonMeta(key: string): LessonMeta | undefined {
  return MONTHLY_SCOPE_AND_SEQUENCE.find((l) => l.key === key);
}

const SLOT_ORDER: Record<string, number> = { week1: 0, week2: 1, week3: 2, week4: 3 };

export function lessonsForMonth(monthIndex: number): LessonMeta[] {
  return MONTHLY_SCOPE_AND_SEQUENCE.filter((l) => l.monthIndex === monthIndex).sort(
    (a, b) => SLOT_ORDER[a.slot ?? "week1"] - SLOT_ORDER[b.slot ?? "week1"]
  );
}
