import type { LessonMeta } from "./types";

/**
 * The full 24-lesson map for "Vora's Classroom." Every lesson has metadata
 * here regardless of whether it's fully authored yet — see
 * lib/curriculum/lessons/index.ts for which ones have complete,
 * Presentation-Player-ready segment content (AUTHORED_LESSON_KEYS) versus
 * planned-but-not-yet-built (everything else). docs/SCOPE_AND_SEQUENCE.md
 * renders this same data as a teacher-facing document.
 */
export const SCOPE_AND_SEQUENCE: LessonMeta[] = [
  // Week 1 — Meet Vora
  {
    key: "w1d1_hello_vora",
    unitKey: "u1_meet_vora",
    week: 1,
    day: 1,
    title: "Hello, Vora!",
    bigIdeas: ["natural_interaction"],
    englishFocus: "Hello / Goodbye / What's your name? / My name is ___.",
    koreanL1Note: "First light exposure to /r/-/l/ contrast via \"Vora\" vs \"hello\" — notice only, no drilling yet (that starts Week 2).",
    objectives: [
      "I can say hello and goodbye in English.",
      "I can tell a friend my name.",
      "I can explain that Vora is a friendly AI helper, not a real robot toy.",
    ],
    standardsNote: "Korean MOE elementary English: greetings & self-introduction (grades 3-4).",
  },
  {
    key: "w1d2_voras_classroom",
    unitKey: "u1_meet_vora",
    week: 1,
    day: 2,
    title: "Vora's Classroom",
    bigIdeas: ["perception"],
    englishFocus: "Classroom object nouns (book, pencil, chair, desk, bag) + \"What is this? It's a ___.\"",
    koreanL1Note: "No consonant clusters in this word set yet — desk (/sk/ cluster) previewed only, not drilled.",
    objectives: [
      "I can name five things in my classroom.",
      "I can ask and answer \"What is this?\"",
    ],
    standardsNote: "Korean MOE elementary English: classroom objects & simple Q&A.",
  },
  {
    key: "w1d3_what_is_ai",
    unitKey: "u1_meet_vora",
    week: 1,
    day: 3,
    title: "What Is AI?",
    bigIdeas: ["perception", "learning"],
    englishFocus: "\"It is / it is not a ___\" statements.",
    koreanL1Note: "\"is/is not\" contraction practice — Korean has no copula-drop equivalent, so model both full and \"isn't\" forms slowly.",
    objectives: [
      "I can sort things into 'smart helper' and 'regular thing.'",
      "I can say \"it is\" and \"it is not\" about a picture.",
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) + Big Idea 3 (Learning) introduced concretely, no jargon.",
  },

  // Week 2 — Animal Friends
  {
    key: "w2d1_animal_safari",
    unitKey: "u2_animal_friends",
    week: 2,
    day: 1,
    title: "Animal Safari",
    bigIdeas: ["perception"],
    englishFocus: "Animal nouns + regular plural -s.",
    koreanL1Note: "Korean has no grammatical plural marking by default — plural -s needs explicit, repeated modeling.",
    objectives: [
      "I can name six animals in English.",
      "I can say \"one cat, two cats.\"",
    ],
    standardsNote: "Korean MOE elementary English: animals & plural nouns.",
  },
  {
    key: "w2d2_how_does_vora_see",
    unitKey: "u2_animal_friends",
    week: 2,
    day: 2,
    title: "How Does Vora See?",
    bigIdeas: ["perception", "learning"],
    englishFocus: "Category nouns: animal vs. vehicle.",
    koreanL1Note: "Reinforces plural -s from Day 1 inside a new sentence frame (\"These are animals.\").",
    objectives: [
      "I can sort pictures into 'animal' and 'vehicle.'",
      "I can explain that Vora learns from many examples, and sometimes guesses wrong.",
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) + Big Idea 3 (Learning), the AI-for-Oceans-style train/guess loop.",
  },
  {
    key: "w2d3_light_or_right",
    unitKey: "u2_animal_friends",
    week: 2,
    day: 3,
    title: "Listen Closely: light or right?",
    bigIdeas: ["perception"],
    englishFocus: "/r/ vs /l/ minimal-pair listening discrimination.",
    koreanL1Note: "Korean has a single liquid consonant realized as either [r] or [l] depending on position, so this contrast is not phonemic in Korean — kids need repeated listening exposure before production is expected.",
    objectives: [
      "I can listen and pick the word I hear: light or right.",
    ],
    standardsNote: "Targets the single highest-frequency Korean-learner pronunciation gap in the research base (see docs/KOREAN_L1_NOTES.md).",
  },

  // Week 3 — Colors & Patterns
  {
    key: "w3d1_rainbow_colors",
    unitKey: "u3_colors_patterns",
    week: 3,
    day: 1,
    title: "Rainbow Colors",
    bigIdeas: [],
    englishFocus: "Color adjectives + \"It is ___.\"",
    koreanL1Note: "Adjective-before-noun order matches Korean (SOV languages generally place adjectives before nouns too) — an easy win, call it out as something that's NOT hard for them.",
    objectives: ["I can name six colors in English."],
    standardsNote: "Korean MOE elementary English: colors & basic adjectives.",
  },
  {
    key: "w3d2_vora_finds_pattern",
    unitKey: "u3_colors_patterns",
    week: 3,
    day: 2,
    title: "Vora Finds the Pattern",
    bigIdeas: ["reasoning", "learning"],
    englishFocus: "Shape nouns (circle, square, triangle, star) + \"same / different.\"",
    koreanL1Note: "Reinforces color adjectives inside a new frame (\"the same color,\" \"a different shape\").",
    objectives: [
      "I can name four shapes in English.",
      "I can find what matches a pattern and what breaks it.",
    ],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — patterns are the foundation of machine learning.",
  },
  {
    key: "w3d3_fan_or_pan",
    unitKey: "u3_colors_patterns",
    week: 3,
    day: 3,
    title: "Listen Closely: fan or pan?",
    bigIdeas: ["perception"],
    englishFocus: "/f/ vs /p/ minimal-pair listening discrimination.",
    koreanL1Note: "Korean has no /f/ phoneme — it's regularly approximated with /p/ or /h/, so this contrast is genuinely new, not just underused.",
    objectives: ["I can listen and pick the word I hear: fan or pan."],
    standardsNote: "Targets the second highest-frequency Korean-learner pronunciation gap in the research base.",
  },

  // Week 4 — My Family & Numbers
  {
    key: "w4d1_my_family",
    unitKey: "u4_my_family",
    week: 4,
    day: 1,
    title: "My Family",
    bigIdeas: [],
    englishFocus: "Family nouns + possessive \"my.\"",
    koreanL1Note: "Korean family terms encode relative age/side of family with no single English equivalent — expect kids to want more precision than \"brother/sister\" gives them; validate that, don't correct it away.",
    objectives: ["I can introduce my family in English."],
    standardsNote: "Korean MOE elementary English: family & possessives.",
  },
  {
    key: "w4d2_count_with_vora",
    unitKey: "u4_my_family",
    week: 4,
    day: 2,
    title: "Count with Vora",
    bigIdeas: ["perception", "reasoning"],
    englishFocus: "Numbers 1-10 + \"I have ___.\" (subject-verb-object word order).",
    koreanL1Note: "Korean is SOV (word-for-word: \"I dog-two have\"); English SVO is the single biggest word-order shift these kids face — build the sentence tile-by-tile so order becomes visible, not abstract.",
    objectives: [
      "I can count to ten in English.",
      "I can build the sentence \"I have two dogs\" in the right word order.",
    ],
    standardsNote: "Numbers (Korean MOE) + AI4K12 Big Idea 1 (Perception) — counting objects in an image is a classic computer-vision task, framed concretely as \"how many does Vora count?\"",
  },
  {
    key: "w4d3_think_or_sink",
    unitKey: "u4_my_family",
    week: 4,
    day: 3,
    title: "Listen Closely: think or sink?",
    bigIdeas: ["perception"],
    englishFocus: "/θ/ (\"th\") vs /s/ minimal-pair listening discrimination.",
    koreanL1Note: "Korean has no dental fricative /θ/; it's regularly substituted with /s/ or /t/.",
    objectives: ["I can listen and pick the word I hear: think or sink."],
    standardsNote: "Third of the four highest-frequency Korean-learner pronunciation gaps targeted this unit.",
  },

  // Week 5 — Food & Choices
  {
    key: "w5d1_yummy_food",
    unitKey: "u5_food_choices",
    week: 5,
    day: 1,
    title: "Yummy Food",
    bigIdeas: [],
    englishFocus: "Food nouns + \"I like ___.\"",
    koreanL1Note: "Includes familiar Korean foods (kimchi, bibimbap) taught in English sentence frames — bridges existing L1 vocabulary confidence into new L2 syntax instead of starting from zero.",
    objectives: ["I can say what food I like in English."],
    standardsNote: "Korean MOE elementary English: food & preferences, culturally localized vocabulary set.",
  },
  {
    key: "w5d2_fruit_or_vegetable",
    unitKey: "u5_food_choices",
    week: 5,
    day: 2,
    title: "Fruit or Vegetable?",
    bigIdeas: ["perception", "learning"],
    englishFocus: "Category nouns: fruit vs. vegetable.",
    koreanL1Note: "Second full train/guess classification loop — checks whether the Week 2 concept transferred to a brand-new category.",
    objectives: ["I can sort foods into 'fruit' and 'vegetable,' and check Vora's guesses."],
    standardsNote: "AI4K12 Big Idea 3 (Learning), second exposure for transfer/retention.",
  },
  {
    key: "w5d3_do_you_like",
    unitKey: "u5_food_choices",
    week: 5,
    day: 3,
    title: "Do You Like...?",
    bigIdeas: [],
    englishFocus: "Yes/no question word order: \"Do you like ___?\"",
    koreanL1Note: "Korean marks questions with rising intonation or a sentence-final particle, without reordering words; English fronts \"do,\" which has no direct Korean equivalent — build the question tile-by-tile, same technique as Week 4's SVO sentence.",
    objectives: ["I can ask a friend \"Do you like ___?\" and answer."],
    standardsNote: "Korean MOE elementary English: yes/no questions; closes out the Food & Choices week.",
  },

  // Week 6 — My Day
  {
    key: "w6d1_my_morning",
    unitKey: "u6_my_day",
    week: 6,
    day: 1,
    title: "My Morning",
    bigIdeas: [],
    englishFocus: "Daily routine verbs (wake up, get dressed, eat breakfast, brush teeth).",
    koreanL1Note: "Verb-final sentence habit (SOV) tends to surface again in longer routine descriptions — keep sentences short (verb + object only) this lesson.",
    objectives: ["I can name four things I do every morning."],
    standardsNote: "Korean MOE elementary English: daily routines.",
  },
  {
    key: "w6d2_give_vora_the_steps",
    unitKey: "u6_my_day",
    week: 6,
    day: 2,
    title: "Give Vora the Steps",
    bigIdeas: ["reasoning"],
    englishFocus: "Sequencing words: first, next, then, last.",
    koreanL1Note: "Sequencing connectives are a genuine gap, not an L1-interference error — Korean has equivalents but young learners rarely produce them unprompted in either language yet.",
    objectives: ["I can put the steps of my morning in the right order."],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — an algorithm is an exact, ordered list of steps.",
  },
  {
    key: "w6d3_bedtime_routine",
    unitKey: "u6_my_day",
    week: 6,
    day: 3,
    title: "First, Next, Then, Last",
    bigIdeas: ["reasoning"],
    englishFocus: "Sequencing words, second routine (bedtime) for transfer.",
    koreanL1Note: "Repeats Day 2's structure with new vocabulary to check transfer, the same design as the Week 2/Week 5 classification pairs.",
    objectives: ["I can order a new routine (getting ready for bed) using first/next/then/last."],
    standardsNote: "Closes out the sequencing/algorithms week with a transfer check.",
  },

  // Week 7 — Robot Helpers
  {
    key: "w7d1_what_can_robots_do",
    unitKey: "u7_robot_helpers",
    week: 7,
    day: 1,
    title: "What Can Robots Do?",
    bigIdeas: ["societal_impact"],
    englishFocus: "Action verbs (clean, cook, drive, fly, swim, talk) + \"can.\"",
    koreanL1Note: "Modal \"can\" has no verb-final counterpart to lean on — model \"Robots can fly\" as a fixed chunk before breaking it into parts.",
    objectives: ["I can say what a robot can do."],
    standardsNote: "Korean MOE elementary English: can/can't for ability.",
  },
  {
    key: "w7d2_robots_at_home_and_school",
    unitKey: "u7_robot_helpers",
    week: 7,
    day: 2,
    title: "Robots at Home and School",
    bigIdeas: ["societal_impact", "perception"],
    englishFocus: "Category nouns: AI helper vs. not AI.",
    koreanL1Note: "Third classification loop; sharpens the AI concept itself rather than drilling new vocabulary (a calculator is smart but not AI — this is the hardest sort in the unit, expect more \"needs practice\" marks here).",
    objectives: ["I can sort helpers into 'AI' and 'not AI,' and explain one example."],
    standardsNote: "AI4K12 Big Idea 5 (Societal Impact) — where AI actually shows up in daily life.",
  },
  {
    key: "w7d3_vora_makes_a_mistake",
    unitKey: "u7_robot_helpers",
    week: 7,
    day: 3,
    title: "Vora Can, Vora Can't",
    bigIdeas: ["societal_impact", "learning"],
    englishFocus: "\"can\" / \"can't\" sentence building.",
    koreanL1Note: "Contrastive can/can't practice — pairs the grammar directly with the AI-limitations concept so the sentence isn't taught in a vacuum.",
    objectives: ["I can build a sentence about something Vora can and can't do."],
    standardsNote: "Closes the loop on AI4K12 Big Idea 5 with a grammar-anchored production task.",
  },

  // Week 8 — Show What You Know
  {
    key: "w8d1_talking_to_ai_safely",
    unitKey: "u8_show_what_you_know",
    week: 8,
    day: 1,
    title: "Talking to AI Safely",
    bigIdeas: ["natural_interaction", "societal_impact"],
    englishFocus: "Reading four short safety statements aloud.",
    koreanL1Note: "Reading-aloud task deliberately kept short (4 lines) — this is a discussion lesson, not a decoding-practice lesson.",
    objectives: ["I can name one rule for talking to an AI safely."],
    standardsNote: "AI4K12 Big Idea 4 (Natural Interaction) + Big Idea 5 (Societal Impact), delivered as static content — see docs/AI_CURRICULUM.md \"Safety\" section for why there's no live chatbot.",
  },
  {
    key: "w8d2_review_carnival",
    unitKey: "u8_show_what_you_know",
    week: 8,
    day: 2,
    title: "Review Carnival",
    bigIdeas: ["perception", "learning", "reasoning"],
    englishFocus: "Cumulative review across all eight weeks of vocabulary and sentence patterns.",
    koreanL1Note: "One round each of every activity engine, using review vocabulary only — this lesson is the closest thing to a formative assessment in the unit.",
    objectives: ["I can play all four Vora games using words I've learned this unit."],
    standardsNote: "Functions as the unit's cumulative formative check — see the participation-marks reporting model in docs/AI_CURRICULUM.md.",
  },
  {
    key: "w8d3_teach_vora_day",
    unitKey: "u8_show_what_you_know",
    week: 8,
    day: 3,
    title: "Teach Vora Day",
    bigIdeas: ["learning", "societal_impact"],
    englishFocus: "Free production: describing a category the class invents, in English.",
    koreanL1Note: "Capstone — teacher-facilitated, small groups pick a category (e.g., \"toys vs. not toys\") and describe it to the class before Vora \"learns\" it live. Ends the unit on production and confidence, not testing.",
    objectives: [
      "I can describe a category I invented, in English, to my class.",
      "I can explain one thing I learned about how AI works.",
    ],
    standardsNote: "Capstone performance assessment closing all five AI4K12 Big Ideas and the unit's core English structures.",
  },
];

export function getLessonMeta(key: string): LessonMeta | undefined {
  return SCOPE_AND_SEQUENCE.find((l) => l.key === key);
}

export function lessonsForWeek(week: number): LessonMeta[] {
  return SCOPE_AND_SEQUENCE.filter((l) => l.week === week).sort((a, b) => (a.day ?? 0) - (b.day ?? 0));
}
