import type { LessonMeta } from "./types";

/**
 * The full 24-lesson map for "Robi's Classroom." Every lesson has metadata
 * here regardless of whether it's fully authored yet — see
 * lib/curriculum/lessons/index.ts for which ones have complete,
 * Presentation-Player-ready segment content (AUTHORED_LESSON_KEYS) versus
 * planned-but-not-yet-built (everything else). docs/SCOPE_AND_SEQUENCE.md
 * renders this same data as a teacher-facing document.
 */
export const SCOPE_AND_SEQUENCE: LessonMeta[] = [
  // Week 1 — Meet Robi
  {
    key: "w1d1_hello_robi",
    unitKey: "u1_meet_robi",
    week: 1,
    day: 1,
    title: { en: "Hello, Robi!", ko: "안녕, 로비!" },
    bigIdeas: ["natural_interaction"],
    englishFocus: { en: "Hello / Goodbye / What's your name? / My name is ___.", ko: "인사 표현과 이름 묻고 답하기" },
    koreanL1Note: "First light exposure to /r/-/l/ contrast via \"Robi\" vs \"hello\" — notice only, no drilling yet (that starts Week 2).",
    objectives: [
      { en: "I can say hello and goodbye in English.", ko: "나는 영어로 인사할 수 있어요." },
      { en: "I can tell a friend my name.", ko: "나는 친구에게 내 이름을 말할 수 있어요." },
      { en: "I can explain that Robi is a friendly AI helper, not a real robot toy.", ko: "나는 로비가 진짜 로봇 장난감이 아니라 다정한 AI 친구라는 것을 설명할 수 있어요." },
    ],
    standardsNote: "Korean MOE elementary English: greetings & self-introduction (초3-4 인사, 자기소개).",
  },
  {
    key: "w1d2_robis_classroom",
    unitKey: "u1_meet_robi",
    week: 1,
    day: 2,
    title: { en: "Robi's Classroom", ko: "로비의 교실" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Classroom object nouns (book, pencil, chair, desk, bag) + \"What is this? It's a ___.\"", ko: "교실 물건 명사와 \"이것은 무엇인가요?\" 표현" },
    koreanL1Note: "No consonant clusters in this word set yet — desk (/sk/ cluster) previewed only, not drilled.",
    objectives: [
      { en: "I can name five things in my classroom.", ko: "나는 교실에 있는 물건 다섯 가지를 말할 수 있어요." },
      { en: "I can ask and answer \"What is this?\"", ko: "나는 \"이것은 무엇인가요?\"를 묻고 답할 수 있어요." },
    ],
    standardsNote: "Korean MOE elementary English: classroom objects & simple Q&A (교실 영어 표현).",
  },
  {
    key: "w1d3_what_is_ai",
    unitKey: "u1_meet_robi",
    week: 1,
    day: 3,
    title: { en: "What Is AI?", ko: "AI란 무엇일까요?" },
    bigIdeas: ["perception", "learning"],
    englishFocus: { en: "\"It is / it is not a ___\" statements.", ko: "\"~이다 / ~이 아니다\" 문장 표현" },
    koreanL1Note: "\"is/is not\" contraction practice — Korean has no copula-drop equivalent, so model both full and \"isn't\" forms slowly.",
    objectives: [
      { en: "I can sort things into 'smart helper' and 'regular thing.'", ko: "나는 물건을 '똑똑한 도우미'와 '보통 물건'으로 분류할 수 있어요." },
      { en: "I can say \"it is\" and \"it is not\" about a picture.", ko: "나는 그림을 보고 \"~이다\", \"~이 아니다\"라고 말할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) + Big Idea 3 (Learning) introduced concretely, no jargon.",
  },

  // Week 2 — Animal Friends
  {
    key: "w2d1_animal_safari",
    unitKey: "u2_animal_friends",
    week: 2,
    day: 1,
    title: { en: "Animal Safari", ko: "동물 사파리" },
    bigIdeas: ["perception"],
    englishFocus: { en: "Animal nouns + regular plural -s.", ko: "동물 명사와 복수형 -s" },
    koreanL1Note: "Korean has no grammatical plural marking by default — plural -s needs explicit, repeated modeling.",
    objectives: [
      { en: "I can name six animals in English.", ko: "나는 영어로 동물 여섯 가지를 말할 수 있어요." },
      { en: "I can say \"one cat, two cats.\"", ko: "나는 \"one cat, two cats\"라고 말할 수 있어요." },
    ],
    standardsNote: "Korean MOE elementary English: animals & plural nouns.",
  },
  {
    key: "w2d2_how_does_robi_see",
    unitKey: "u2_animal_friends",
    week: 2,
    day: 2,
    title: { en: "How Does Robi See?", ko: "로비는 어떻게 볼까요?" },
    bigIdeas: ["perception", "learning"],
    englishFocus: { en: "Category nouns: animal vs. vehicle.", ko: "분류 명사: 동물 대 탈것" },
    koreanL1Note: "Reinforces plural -s from Day 1 inside a new sentence frame (\"These are animals.\").",
    objectives: [
      { en: "I can sort pictures into 'animal' and 'vehicle.'", ko: "나는 그림을 '동물'과 '탈것'으로 분류할 수 있어요." },
      { en: "I can explain that Robi learns from many examples, and sometimes guesses wrong.", ko: "나는 로비가 여러 예시를 보고 배우며, 가끔 틀리게 추측한다는 것을 설명할 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 1 (Perception) + Big Idea 3 (Learning), the AI-for-Oceans-style train/guess loop.",
  },
  {
    key: "w2d3_light_or_right",
    unitKey: "u2_animal_friends",
    week: 2,
    day: 3,
    title: { en: "Listen Closely: light or right?", ko: "잘 들어보세요: light일까요, right일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/r/ vs /l/ minimal-pair listening discrimination.", ko: "/r/와 /l/ 최소 대립쌍 듣기 구별" },
    koreanL1Note: "Korean has a single liquid phoneme /ㄹ/ realized as either [r] or [l] depending on position, so this contrast is not phonemic in Korean — kids need repeated listening exposure before production is expected.",
    objectives: [
      { en: "I can listen and pick the word I hear: light or right.", ko: "나는 듣고 들은 단어를 고를 수 있어요: light 또는 right." },
    ],
    standardsNote: "Targets the single highest-frequency Korean-learner pronunciation gap in the research base (see docs/KOREAN_L1_NOTES.md).",
  },

  // Week 3 — Colors & Patterns
  {
    key: "w3d1_rainbow_colors",
    unitKey: "u3_colors_patterns",
    week: 3,
    day: 1,
    title: { en: "Rainbow Colors", ko: "무지개 색깔" },
    bigIdeas: [],
    englishFocus: { en: "Color adjectives + \"It is ___.\"", ko: "색깔 형용사와 \"그것은 ~이다\" 표현" },
    koreanL1Note: "Adjective-before-noun order matches Korean (SOV languages generally place adjectives before nouns too) — an easy win, call it out as something that's NOT hard for them.",
    objectives: [{ en: "I can name six colors in English.", ko: "나는 영어로 색깔 여섯 가지를 말할 수 있어요." }],
    standardsNote: "Korean MOE elementary English: colors & basic adjectives.",
  },
  {
    key: "w3d2_robi_finds_pattern",
    unitKey: "u3_colors_patterns",
    week: 3,
    day: 2,
    title: { en: "Robi Finds the Pattern", ko: "로비가 패턴을 찾아요" },
    bigIdeas: ["reasoning", "learning"],
    englishFocus: { en: "Shape nouns (circle, square, triangle, star) + \"same / different.\"", ko: "모양 명사와 \"같다 / 다르다\" 표현" },
    koreanL1Note: "Reinforces color adjectives inside a new frame (\"the same color,\" \"a different shape\").",
    objectives: [
      { en: "I can name four shapes in English.", ko: "나는 영어로 모양 네 가지를 말할 수 있어요." },
      { en: "I can find what matches a pattern and what breaks it.", ko: "나는 패턴에 맞는 것과 맞지 않는 것을 찾을 수 있어요." },
    ],
    standardsNote: "AI4K12 Big Idea 3 (Learning) — patterns are the foundation of machine learning.",
  },
  {
    key: "w3d3_fan_or_pan",
    unitKey: "u3_colors_patterns",
    week: 3,
    day: 3,
    title: { en: "Listen Closely: fan or pan?", ko: "잘 들어보세요: fan일까요, pan일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/f/ vs /p/ minimal-pair listening discrimination.", ko: "/f/와 /p/ 최소 대립쌍 듣기 구별" },
    koreanL1Note: "Korean has no /f/ phoneme — it's regularly approximated with /p/ (ㅍ) or /h/ (ㅎ), so this contrast is genuinely new, not just underused.",
    objectives: [{ en: "I can listen and pick the word I hear: fan or pan.", ko: "나는 듣고 들은 단어를 고를 수 있어요: fan 또는 pan." }],
    standardsNote: "Targets the second highest-frequency Korean-learner pronunciation gap in the research base.",
  },

  // Week 4 — My Family & Numbers
  {
    key: "w4d1_my_family",
    unitKey: "u4_my_family",
    week: 4,
    day: 1,
    title: { en: "My Family", ko: "우리 가족" },
    bigIdeas: [],
    englishFocus: { en: "Family nouns + possessive \"my.\"", ko: "가족 명사와 소유격 \"my\"" },
    koreanL1Note: "Korean family terms encode relative age/side of family (형/오빠, 누나/언니) with no single English equivalent — expect kids to want more precision than \"brother/sister\" gives them; validate that, don't correct it away.",
    objectives: [{ en: "I can introduce my family in English.", ko: "나는 영어로 우리 가족을 소개할 수 있어요." }],
    standardsNote: "Korean MOE elementary English: family & possessives.",
  },
  {
    key: "w4d2_count_with_robi",
    unitKey: "u4_my_family",
    week: 4,
    day: 2,
    title: { en: "Count with Robi", ko: "로비와 함께 세어보아요" },
    bigIdeas: ["perception", "reasoning"],
    englishFocus: { en: "Numbers 1-10 + \"I have ___.\" (subject-verb-object word order).", ko: "숫자 1-10과 \"I have ___.\" 문장 어순" },
    koreanL1Note: "Korean is SOV (\"나는 개를 두 마리 가지고 있어요\" = I dogs two have); English SVO is the single biggest word-order shift these kids face — build the sentence tile-by-tile so order becomes visible, not abstract.",
    objectives: [
      { en: "I can count to ten in English.", ko: "나는 영어로 10까지 셀 수 있어요." },
      { en: "I can build the sentence \"I have two dogs\" in the right word order.", ko: "나는 \"I have two dogs\"를 올바른 어순으로 만들 수 있어요." },
    ],
    standardsNote: "Numbers (Korean MOE) + AI4K12 Big Idea 1 (Perception) — counting objects in an image is a classic computer-vision task, framed concretely as \"how many does Robi count?\"",
  },
  {
    key: "w4d3_think_or_sink",
    unitKey: "u4_my_family",
    week: 4,
    day: 3,
    title: { en: "Listen Closely: think or sink?", ko: "잘 들어보세요: think일까요, sink일까요?" },
    bigIdeas: ["perception"],
    englishFocus: { en: "/θ/ (\"th\") vs /s/ minimal-pair listening discrimination.", ko: "/θ/(th)와 /s/ 최소 대립쌍 듣기 구별" },
    koreanL1Note: "Korean has no dental fricative /θ/; it's regularly substituted with /s/ (ㅅ) or /t/ (ㅌ).",
    objectives: [{ en: "I can listen and pick the word I hear: think or sink.", ko: "나는 듣고 들은 단어를 고를 수 있어요: think 또는 sink." }],
    standardsNote: "Third of the four highest-frequency Korean-learner pronunciation gaps targeted this unit.",
  },

  // Week 5 — Food & Choices
  {
    key: "w5d1_yummy_food",
    unitKey: "u5_food_choices",
    week: 5,
    day: 1,
    title: { en: "Yummy Food", ko: "맛있는 음식" },
    bigIdeas: [],
    englishFocus: { en: "Food nouns + \"I like ___.\"", ko: "음식 명사와 \"I like ___.\" 표현" },
    koreanL1Note: "Includes familiar Korean foods (kimchi, bibimbap) taught in English sentence frames — bridges existing L1 vocabulary confidence into new L2 syntax instead of starting from zero.",
    objectives: [{ en: "I can say what food I like in English.", ko: "나는 영어로 좋아하는 음식을 말할 수 있어요." }],
    standardsNote: "Korean MOE elementary English: food & preferences, culturally localized vocabulary set.",
  },
  {
    key: "w5d2_fruit_or_vegetable",
    unitKey: "u5_food_choices",
    week: 5,
    day: 2,
    title: { en: "Fruit or Vegetable?", ko: "과일일까요, 채소일까요?" },
    bigIdeas: ["perception", "learning"],
    englishFocus: { en: "Category nouns: fruit vs. vegetable.", ko: "분류 명사: 과일 대 채소" },
    koreanL1Note: "Second full train/guess classification loop — checks whether the Week 2 concept transferred to a brand-new category.",
    objectives: [{ en: "I can sort foods into 'fruit' and 'vegetable,' and check Robi's guesses.", ko: "나는 음식을 '과일'과 '채소'로 분류하고 로비의 추측을 확인할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 3 (Learning), second exposure for transfer/retention.",
  },
  {
    key: "w5d3_do_you_like",
    unitKey: "u5_food_choices",
    week: 5,
    day: 3,
    title: { en: "Do You Like...?", ko: "Do you like...?" },
    bigIdeas: [],
    englishFocus: { en: "Yes/no question word order: \"Do you like ___?\"", ko: "Yes/no 의문문 어순: \"Do you like ___?\"" },
    koreanL1Note: "Korean marks questions with intonation/particle (~니?/~까?) without reordering words; English fronts \"do,\" which has no direct Korean equivalent — build the question tile-by-tile, same technique as Week 4's SVO sentence.",
    objectives: [{ en: "I can ask a friend \"Do you like ___?\" and answer.", ko: "나는 친구에게 \"Do you like ___?\"라고 묻고 답할 수 있어요." }],
    standardsNote: "Korean MOE elementary English: yes/no questions; closes out the Food & Choices week.",
  },

  // Week 6 — My Day
  {
    key: "w6d1_my_morning",
    unitKey: "u6_my_day",
    week: 6,
    day: 1,
    title: { en: "My Morning", ko: "나의 아침" },
    bigIdeas: [],
    englishFocus: { en: "Daily routine verbs (wake up, get dressed, eat breakfast, brush teeth).", ko: "일상 루틴 동사" },
    koreanL1Note: "Verb-final sentence habit (SOV) tends to surface again in longer routine descriptions — keep sentences short (verb + object only) this lesson.",
    objectives: [{ en: "I can name four things I do every morning.", ko: "나는 매일 아침에 하는 일 네 가지를 말할 수 있어요." }],
    standardsNote: "Korean MOE elementary English: daily routines.",
  },
  {
    key: "w6d2_give_robi_the_steps",
    unitKey: "u6_my_day",
    week: 6,
    day: 2,
    title: { en: "Give Robi the Steps", ko: "로비에게 순서를 알려줘요" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Sequencing words: first, next, then, last.", ko: "순서 표현: first, next, then, last" },
    koreanL1Note: "Sequencing connectives are a genuine gap, not an L1-interference error — Korean has equivalents (먼저/그다음/마지막) but young learners rarely produce them unprompted in either language yet.",
    objectives: [{ en: "I can put the steps of my morning in the right order.", ko: "나는 아침 루틴의 순서를 올바르게 배열할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 2 (Representation & Reasoning) — an algorithm is an exact, ordered list of steps.",
  },
  {
    key: "w6d3_bedtime_routine",
    unitKey: "u6_my_day",
    week: 6,
    day: 3,
    title: { en: "First, Next, Then, Last", ko: "First, Next, Then, Last" },
    bigIdeas: ["reasoning"],
    englishFocus: { en: "Sequencing words, second routine (bedtime) for transfer.", ko: "순서 표현, 두 번째 루틴(잠자리 준비)으로 전이 연습" },
    koreanL1Note: "Repeats Day 2's structure with new vocabulary to check transfer, the same design as the Week 2/Week 5 classification pairs.",
    objectives: [{ en: "I can order a new routine (getting ready for bed) using first/next/then/last.", ko: "나는 새로운 루틴(잠자리 준비)을 first/next/then/last를 사용해 순서대로 말할 수 있어요." }],
    standardsNote: "Closes out the sequencing/algorithms week with a transfer check.",
  },

  // Week 7 — Robot Helpers
  {
    key: "w7d1_what_can_robots_do",
    unitKey: "u7_robot_helpers",
    week: 7,
    day: 1,
    title: { en: "What Can Robots Do?", ko: "로봇은 무엇을 할 수 있을까요?" },
    bigIdeas: ["societal_impact"],
    englishFocus: { en: "Action verbs (clean, cook, drive, fly, swim, talk) + \"can.\"", ko: "동작 동사와 \"can\"" },
    koreanL1Note: "Modal \"can\" has no verb-final counterpart to lean on — model \"Robots can fly\" as a fixed chunk before breaking it into parts.",
    objectives: [{ en: "I can say what a robot can do.", ko: "나는 로봇이 할 수 있는 일을 말할 수 있어요." }],
    standardsNote: "Korean MOE elementary English: can/can't for ability.",
  },
  {
    key: "w7d2_robots_at_home_and_school",
    unitKey: "u7_robot_helpers",
    week: 7,
    day: 2,
    title: { en: "Robots at Home and School", ko: "집과 학교의 로봇" },
    bigIdeas: ["societal_impact", "perception"],
    englishFocus: { en: "Category nouns: AI helper vs. not AI.", ko: "분류 명사: AI 도우미 대 AI가 아닌 것" },
    koreanL1Note: "Third classification loop; sharpens the AI concept itself rather than drilling new vocabulary (a calculator is smart but not AI — this is the hardest sort in the unit, expect more \"needs practice\" marks here).",
    objectives: [{ en: "I can sort helpers into 'AI' and 'not AI,' and explain one example.", ko: "나는 도우미를 'AI'와 'AI가 아닌 것'으로 분류하고 한 가지 예를 설명할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 5 (Societal Impact) — where AI actually shows up in daily life.",
  },
  {
    key: "w7d3_robi_makes_a_mistake",
    unitKey: "u7_robot_helpers",
    week: 7,
    day: 3,
    title: { en: "Robi Can, Robi Can't", ko: "로비가 할 수 있는 일, 할 수 없는 일" },
    bigIdeas: ["societal_impact", "learning"],
    englishFocus: { en: "\"can\" / \"can't\" sentence building.", ko: "\"can\" / \"can't\" 문장 만들기" },
    koreanL1Note: "Contrastive can/can't practice — pairs the grammar directly with the AI-limitations concept so the sentence isn't taught in a vacuum.",
    objectives: [{ en: "I can build a sentence about something Robi can and can't do.", ko: "나는 로비가 할 수 있는 일과 할 수 없는 일에 대한 문장을 만들 수 있어요." }],
    standardsNote: "Closes the loop on AI4K12 Big Idea 5 with a grammar-anchored production task.",
  },

  // Week 8 — Show What You Know
  {
    key: "w8d1_talking_to_ai_safely",
    unitKey: "u8_show_what_you_know",
    week: 8,
    day: 1,
    title: { en: "Talking to AI Safely", ko: "AI와 안전하게 대화해요" },
    bigIdeas: ["natural_interaction", "societal_impact"],
    englishFocus: { en: "Reading four short safety statements aloud.", ko: "네 가지 짧은 안전 수칙 소리 내어 읽기" },
    koreanL1Note: "Reading-aloud task deliberately kept short (4 lines) — this is a discussion lesson, not a decoding-practice lesson.",
    objectives: [{ en: "I can name one rule for talking to an AI safely.", ko: "나는 AI와 안전하게 대화하기 위한 규칙을 한 가지 말할 수 있어요." }],
    standardsNote: "AI4K12 Big Idea 4 (Natural Interaction) + Big Idea 5 (Societal Impact), delivered as static content — see docs/AI_CURRICULUM.md \"Safety\" section for why there's no live chatbot.",
  },
  {
    key: "w8d2_review_carnival",
    unitKey: "u8_show_what_you_know",
    week: 8,
    day: 2,
    title: { en: "Review Carnival", ko: "복습 카니발" },
    bigIdeas: ["perception", "learning", "reasoning"],
    englishFocus: { en: "Cumulative review across all eight weeks of vocabulary and sentence patterns.", ko: "8주간 배운 어휘와 문장 패턴 종합 복습" },
    koreanL1Note: "One round each of every activity engine, using review vocabulary only — this lesson is the closest thing to a formative assessment in the unit.",
    objectives: [{ en: "I can play all four Robi games using words I've learned this unit.", ko: "나는 이번 학기에 배운 단어로 로비의 네 가지 게임을 모두 할 수 있어요." }],
    standardsNote: "Functions as the unit's cumulative formative check — see the participation-marks reporting model in docs/AI_CURRICULUM.md.",
  },
  {
    key: "w8d3_teach_robi_day",
    unitKey: "u8_show_what_you_know",
    week: 8,
    day: 3,
    title: { en: "Teach Robi Day", ko: "로비를 가르치는 날" },
    bigIdeas: ["learning", "societal_impact"],
    englishFocus: { en: "Free production: describing a category the class invents, in English.", ko: "학급이 만든 분류를 영어로 설명하는 자유 발화 활동" },
    koreanL1Note: "Capstone — teacher-facilitated, small groups pick a category (e.g., \"toys vs. not toys\") and describe it to the class before Robi \"learns\" it live. Ends the unit on production and confidence, not testing.",
    objectives: [
      { en: "I can describe a category I invented, in English, to my class.", ko: "나는 내가 만든 분류를 영어로 반 친구들에게 설명할 수 있어요." },
      { en: "I can explain one thing I learned about how AI works.", ko: "나는 AI가 작동하는 방식에 대해 배운 것을 한 가지 설명할 수 있어요." },
    ],
    standardsNote: "Capstone performance assessment closing all five AI4K12 Big Ideas and the unit's core English structures.",
  },
];

export function getLessonMeta(key: string): LessonMeta | undefined {
  return SCOPE_AND_SEQUENCE.find((l) => l.key === key);
}

export function lessonsForWeek(week: number): LessonMeta[] {
  return SCOPE_AND_SEQUENCE.filter((l) => l.week === week).sort((a, b) => a.day - b.day);
}
